replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.27"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

healthChecks:
  enabled: true
  startupProbe:
    path: "/healthz"
  livenessProbe:
    path: "/healthz"
  readinessProbe:
    path: "/ready"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceMonitor:
  enabled: false

appSettings:
  greeting: "Hello from helm-library!"
