name: Docs

on:
  push:
    branches: [main]
    paths:
      - "charts/**"
      - "README.md"
      - "CONTRIBUTING.md"

permissions:
  contents: write

jobs:
  generate-docs:
    name: Generate Helm Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up helm-docs
        uses: norwoodj/helm-docs-action@v1
        with:
          working-dir: charts/helm-library
          output-file: README.md

      - name: Commit docs changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate helm-docs"
          file_pattern: "charts/helm-library/README.md"
